<#
.SYNOPSIS
  Scans subdirectories for games and generates/updates games.json for the AI Arcade.
.DESCRIPTION
  Looks for index.html in each subdirectory. If a game.json exists in the
  subdirectory, its values are used. Otherwise, metadata is extracted from
  index.html (title tag). Run this after adding a new game folder.
.EXAMPLE
  .\refresh-games.ps1
#>

$root = $PSScriptRoot
$gamesPath = Join-Path $root "games.json"
$gameDirs = Get-ChildItem -Path $root -Directory

$games = @()

foreach ($dir in $gameDirs) {
    $folderName = $dir.Name
    $gameJsonPath = Join-Path $dir.FullName "game.json"
    $indexPath = Join-Path $dir.FullName "index.html"

    # Skip directories without an index.html
    if (-not (Test-Path $indexPath)) {
        Write-Host "  [SKIP] $folderName (no index.html)"
        continue
    }

    Write-Host "  [FOUND] $folderName"

    # Derive a stable id from the folder name
    $id = $folderName.ToLower() -replace '[^a-z0-9]+', '-' -replace '^-|-$', ''

    $game = @{
        id     = $id
        folder = $folderName
        path   = "$folderName/index.html"
    }

    if (Test-Path $gameJsonPath) {
        # Read metadata from game.json
        try {
            $meta = Get-Content $gameJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
            $game.title       = $meta.title
            $game.emoji       = $meta.emoji
            $game.description = $meta.description
            $game.controls    = $meta.controls
            $game.color       = $meta.color
            if ($meta.bgColor) { $game.bgColor = $meta.bgColor }
            Write-Host "    >> using game.json metadata"
        }
        catch {
            Write-Host "    [WARN] game.json invalid, falling back to auto-detect" -ForegroundColor Yellow
            $meta = $null
        }
    }

    if (-not $game.title) {
        # Auto-detect: extract <title> from index.html
        try {
            $html = Get-Content $indexPath -Raw -Encoding UTF8
            if ($html -match '<title>\s*(.*?)\s*</title>') {
                $game.title = $matches[1].Trim()
            }
            else {
                $game.title = $folderName
            }
        }
        catch {
            $game.title = $folderName
        }
        $game.description = ""
        $game.controls = ""

        # Generate a deterministic color from folder name (simple hash)
        $hash = 0
        foreach ($ch in $folderName.ToCharArray()) { $hash = $hash * 31 + [int]$ch; $hash = $hash -band 0x7FFFFFFF }
        [int]$r = 55 + ($hash % 160)
        [int]$g = 55 + (($hash / 3) % 160)
        [int]$b = 55 + (($hash / 7) % 160)
        $game.color = "#{0:x2}{1:x2}{2:x2}" -f $r, $g, $b
        $game.autoGenerated = $true
        Write-Host "    >> auto-detected title: '$($game.title)'"
    }

    $games += [PSCustomObject]$game
}

if ($games.Count -eq 0) {
    Write-Host "`nNo games found (no subdirectories with index.html)." -ForegroundColor Yellow
}
else {
    # Generate games.json (human-readable)
    $json = $games | ConvertTo-Json -Depth 4
    $json | Set-Content $gamesPath -Encoding UTF8

    # Generate games-data.js (embedded script for file:// compatibility)
    $jsPath = Join-Path $root "games-data.js"
    $jsContent = "window.ARCADE_GAMES = " + $json + ";"
    $jsContent | Set-Content $jsPath -Encoding UTF8

    Write-Host "`nDone! Generated games.json and games-data.js with $($games.Count) game(s)." -ForegroundColor Green
}
